# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geo For All - LSU
brief-intro: FOSS4G Organization at Louisiana State University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geoforall-lsu.github.io" # the base hostname & protocol for your site

# next meeting info
next_meeting_date: Wed, Feb 21, 1pm, 2020
next_meeting_location: Design 308

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username:  geoforall-lsu
email: acox42@lsu.edu
linkedIn_username: 
dribbble_username:

description_footer:

# comments
disqus_shortname: geoforall-lsu

# statistic analysis
google_analytics_id: UA-66914064-2 # google id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
gems: [jekyll-paginate]
paginate: 6
